---
version: '3.7'
services:
  ## Postgres Docker Compose Config
  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: serkowski
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always


  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
        
  zookeeper-ms:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper-ms
    container_name: zookeeper-ms
    networks:
      - serkowski_net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000      
      
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    hostname: zoonavigator
    networks:
      - serkowski_net
    ports:
      - "9000:9000"
    environment:
      AUTO_CONNECT_CONNECTION_STRING: zookeeper-ms:2181

  ## Order.java-Service Docker Compose Config
  order-service:
    container_name: order-service
    build: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5431/order-service
    depends_on:
      - postgres-order
        
networks:
  serkowski_net:
    driver: bridge        